server:
  port: 8090
spring:
  application:
    name: jobportal_v2
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # creates/updates tables automatically
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        # paging start at 1
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
    upload-file:
      base-path: /home/tienp/Learning/Java/upload_v2/
jwt:
  key: ${JWT_KEY}
  expiration: ${JWT_EXPIRATION}