server:
  port: 8090
spring:
  application:
    name: jobportal_v2
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # creates/updates tables automatically
    properties:
      hibernate:
        format_sql: true
jwt:
  key: ${JWT_KEY}
  expiration: ${JWT_EXPIRATION}

